# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
locale: "en"
title: Pachyderm Pedals 
email: pachydermpedals@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Pachyderm Pedals are hand wired pedals built in the USA from quality parts. 
  The line of Pandemic Pedals started when the pandemic did and I have building 
  ever since. I enjoy being able to create one of a kind hand painted pedals.

logo: /assets/images/logo.png

minimal_mistakes_skin: "dirt"
search: true
logo: /assets/images/logo.png

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache


author:
  name   : "Mike Fabulosa"
  avatar : "/assets/images/bio-photo.jpg"
  bio    : "After watching a YouTube video on building pedals I started a new hobby which became an obsession."
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://www.pandemicpedals.com"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/PachydermP"
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook"
      url: "https://www.facebook.com/pachydermpedals/"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/pandemicpedals/"
    - label: "Youtube"
      icon: "fab fa-fw fa-youtube"
      url: "https://www.youtube.com/channel/UCvBC1msfVJoEQU7YwudcIUg"

footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/PachydermP"
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook"
      url: "https://www.facebook.com/pachydermpedals/"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/pandemicpedals/"
    - label: "Youtube"
      icon: "fab fa-fw fa-youtube"
      url: "https://www.youtube.com/channel/UCvBC1msfVJoEQU7YwudcIUg"


excerpt: "This post should [...]"
header:
  overlay_image: /assets/images/header.jpg
  overlay_filter: 0.5 # same as adding an opacity of 0.5 to a black background
  caption: "Pandemic Pedal Collection 2020-09-13"
  actions:
    - label: "Pedals"
      url: "pedals.html"
    - label: "Tutorials"
      url: "tutorials.html"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: archive
      show_date: true
      author_profile: false
      read_time: true
      comments: true
      share: true
      related: true
  # _tutorials
  - scope:
      path: ""
      type: tutorials
    values:
      layout: single
      show_date: true
      author_profile: false
      read_time: true
      comments: true
      share: true
      related: true
  # _pedals
  - scope:
      path: ""
      type: pedals
    values:
      layout: single
      show_date: true
      author_profile: false
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

collections_dir: /collections/

collections:
  tutorials:
    output: true
  pedals:
    output: true
  guitars:
    output: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
